In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('homeprices.csv');
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
X = df[['area']]
y = df['price']

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [ ]:
# GENERATES THE m -> Slope
model.coef_

array([135.78767123])

In [ ]:
# GENERATES THE c -> Intercept
model.intercept_

np.float64(180616.43835616432)

In [ ]:
# Make prediction for 3800 area
# y = mX + c
y = 135.78767123*3800 + 180616.43835616432
y

696609.5890301643

In [ ]:
# INSTEAD OF DOING MANUALLY WE CAN USE THE BELOW ONCE DIRECTLY
model.predict([[3800]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([696609.5890411])

In [ ]:
# JUST AN EXAMPLE PRACTICE
135.78767123*420 + 180616.43835616432

237647.2602727643

In [ ]:
model.predict([[420]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([237647.26027397])

In [ ]:
train_df = pd.read_csv('house_train.csv')
test_df = pd.read_csv('house_test.csv')
train_df
# test_df

ID  Location Paint_Color  Lot_Width  Lot_Depth  Year_Sold  Year_Built  \
0        1    Suburb       Green        134        NaN       2020        1990   
1        2  Downtown       Green         76       93.0       2025        2019   
2        3    Suburb      Yellow         91       83.0       2019        2003   
3        4    Suburb       Green         26       21.0       2022        1995   
4        5     Rural         Red        138       85.0       2017        1980   
...    ...       ...         ...        ...        ...        ...         ...   
1995  1996    Suburb      Yellow        145       60.0       2016        1988   
1996  1997  Downtown         Red        117       59.0       2024        2002   
1997  1998     Rural      Yellow         45        NaN       2022        1990   
1998  1999     Rural         Red         67        NaN       2016        1970   
1999  2000     Rural       Green         85      133.0       2017        2000   

      Living_Area  Num_Rooms      Price  
0             813          6  1548800.0  
1            3093          6  1974800.0  
2            2845          3  2466950.0  
3            1837          3   968700.0  
4            4928          8  2570700.0  
...           ...        ...        ...  
1995          984          8  1600600.0  
1996         1045          3  1685450.0  
1997         1038          3   655700.0  
1998         1319          8  1530300.0  
1999         4707          5  2977430.0  

[2000 rows x 10 columns]

In [ ]:
train_df.isnull().sum()

ID               0
Location         0
Paint_Color      0
Lot_Width        0
Lot_Depth      279
Year_Sold        0
Year_Built       0
Living_Area      0
Num_Rooms        0
Price            0
dtype: int64

In [ ]:
# FILLING MISSING VALUES IN THE NULL POSITIONS USING MEDIAN AND FILLNA
train_df['Lot_Depth'] = train_df['Lot_Depth'].fillna(train_df['Lot_Depth'].median())

In [ ]:
# ONE HOT ENCODING ON "LOCATION"
train_df = pd.get_dummies(train_df, columns=['Location'])
test_df = pd.get_dummies(test_df, columns=['Location'])

In [ ]:
# REQUIREMENTS
X_test = train_df[['Lot_Width','Lot_Depth', 'Year_Sold', 'Year_Built', 'Living_Area', 'Num_Rooms', 'Location_Downtown', 'Location_Rural', 'Location_Suburb']]
y = train_df['Price']

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X_test,y)

LinearRegression()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
test_ids = test_df['ID']

median_lot_depth_train = train_df['Lot_Depth'].median()
test_df['Lot_Depth'] = test_df['Lot_Depth'].fillna(median_lot_depth_train)

X_test_for_prediction = test_df[['Lot_Width','Lot_Depth', 'Year_Sold', 'Year_Built', 'Living_Area', 'Num_Rooms', 'Location_Downtown', 'Location_Rural', 'Location_Suburb']]

predictions = model.predict(X_test_for_prediction)

submission = pd.DataFrame({
    'ID': test_ids,
    'Price': predictions
})

submission.to_csv('submission.csv', index=False)

In [ ]:
# REMOVING OUTLIERS
